[package]
name = "fuzzr"
version = "0.1.0"
authors = [
  "Hunter Trujillo <cryptoquick@pm.me>",
  "David Croisant <kn0wmad@protonmail.com>",
]
edition = "2018"

[dependencies]
# Debugging
pretty_env_logger = "0.4"
# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# System
directories-next = "2.0"
env_logger = "0.8"
tokio = "0.2"
# UI
iced = { version = "0.2", features = [
  "wgpu",
  "default_system_font",
  "qr_code",
  "image",
] }
iced_native = "0.3"
# Data
sled = "0.34"
iced_futures = "0.2.0"
reqwest = "0.10.9"
# Experimental Rust-native IPFS Embed
# ipfs-embed = "0.9"
# ipfs-embed-core = "0.9"
# libipld = "0.8"
