[package]
name = "fuzzr"
version = "0.0.2"
authors = [
  "Hunter Trujillo <cryptoquick@pm.me>",
  "David Croisant <kn0wmad@protonmail.com>",
]
edition = "2018"
license = "Unlicense"

[build]
incremental = true

[profile.release]
# strip = "symbols" # https://github.com/rust-lang/rust/issues/72110
lto = true
codegen-units = 1

[dev-dependencies]
tempfile = "3.1"

[dependencies]
# Language
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
derivative = "2.1"
pin-project = "1.0"
# Debugging
pretty_env_logger = "0.4"
log = "0.4"
anyhow = "1.0"
# System
# async-std = "=1.8.0"
tokio = { version = "1.0", features = ["full"] }
crossbeam-deque = "0.8"
# parallel-stream = "2.1"
directories-next = "2.0"
num_cpus = "1.13"
rayon = "1.5"
# UI
iced = { git = "https://github.com/hecrj/iced.git", rev = "f8aef03456ecc185098b6305a8cd0e22f5297d06", features = [
  "wgpu",
  "default_system_font",
  "image",
  "tokio"
] }
iced_native = { git = "https://github.com/hecrj/iced.git", rev = "f8aef03456ecc185098b6305a8cd0e22f5297d06" }
iced_futures = { git = "https://github.com/hecrj/iced.git", rev = "f8aef03456ecc185098b6305a8cd0e22f5297d06" }
# IPFS
ipfs-embed = { git = "https://github.com/ipfs-rust/ipfs-embed.git", rev = "a852c5f637dfb08a97d5a08a08cc86e81f5c9d96" }
libipld = "0.8"
# Data
sled = "0.34"
image = "0.23"
infer = "0.3"
walkdir = "2.3"
tokio-test = "0.4"
# Todo
# ipld-collections = "0.3.0"
# reqwest = "0.10"
