[package]
name = "fuzzr"
version = "0.0.2"
authors = [
  "Hunter Trujillo <cryptoquick@pm.me>",
  "David Croisant <kn0wmad@protonmail.com>",
]
edition = "2018"
license = "Unlicense"
description = "P2P platform for publishing content, self-hosting, decentralized curation, and more."
homepage = "https://fuzzr.net"
repository = "https://github.com/FuzzrNet/Fuzzr"
documentation = "https://github.com/FuzzrNet/Fuzzr/tree/main/docs"

[build]
incremental = true

[profile.release]
# strip = "symbols" # https://github.com/rust-lang/rust/issues/72110
lto = true
codegen-units = 1

[dev-dependencies]
tempfile = "3.1"

[dependencies]
# Debugging
pretty_env_logger = "0.4"
log = "0.4"
anyhow = "1.0"
# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# System
directories-next = "2.0"
async-std = "1.8"
# UI
iced = { version = "0.2", git = "https://github.com/hecrj/iced.git", rev = "f8aef03456ecc185098b6305a8cd0e22f5297d06", features = [
  "wgpu",
  "default_system_font",
  "image",
  "async-std"
] }
iced_native = { version = "0.3", git = "https://github.com/hecrj/iced.git", rev = "f8aef03456ecc185098b6305a8cd0e22f5297d06" }
iced_futures = { version = "0.2", git = "https://github.com/hecrj/iced.git", rev = "f8aef03456ecc185098b6305a8cd0e22f5297d06" }
# Data
# reqwest = "0.10"
sled = "0.34"
image = "0.23"
infer = "0.3"
# IPFS
ipfs-embed = { version = "0.9", git = "https://github.com/ipfs-rust/ipfs-embed.git", rev = "a852c5f637dfb08a97d5a08a08cc86e81f5c9d96" }
libipld = "0.8"
# ipld-collections = "0.3.0"
