[package]
name = "fuzzr"
version = "0.1.0"
authors = [
  "Hunter Trujillo <cryptoquick@pm.me>",
  "David Croisant <kn0wmad@protonmail.com>",
]
edition = "2018"
publish = false
license = "Unlicense"

[build]
incremental = true

[dependencies]
# Debugging
pretty_env_logger = "0.4"
log = "0.4"
# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# System
directories-next = "2.0"
async-std = "1.8"
anyhow = "1.0"
# UI
iced = { git = "https://github.com/hecrj/iced.git", rev = "f8aef03456ecc185098b6305a8cd0e22f5297d06", features = [
  "wgpu",
  "default_system_font",
  "image",
  "async-std"
] }
iced_native = { git = "https://github.com/hecrj/iced.git", rev = "f8aef03456ecc185098b6305a8cd0e22f5297d06" }
iced_futures = { git = "https://github.com/hecrj/iced.git", rev = "f8aef03456ecc185098b6305a8cd0e22f5297d06" }
# Data
reqwest = "0.10"
sled = "0.34"
image = "0.23"
infer = "0.3"
# IPFS
ipfs-embed = { git = "https://github.com/ipfs-rust/ipfs-embed.git", rev = "a852c5f637dfb08a97d5a08a08cc86e81f5c9d96" }
libipld = "0.8"
# ipld-collections = "0.3.0"
