[package]
name = "fuzzr"
version = "0.1.0"
authors = [
  "Hunter Trujillo <cryptoquick@pm.me>",
  "David Croisant <kn0wmad@protonmail.com>",
]
edition = "2018"
publish = false
license = "Unlicense"

[dependencies]
# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# System
directories-next = "2.0"
pretty_env_logger = "0.4"
log = "0.4"
async-std = "1.8"
anyhow = "1.0"
parking_lot = "0.11"
# UI
iced = { version = "0.2", features = [
  "wgpu",
  "default_system_font",
  "image",
  "async-std"
] }
iced_native = "0.3"
iced_futures = "0.2.0"
# Data
sled = "0.34"
image = "0.23"
reqwest = "0.10"
# Experimental Rust-native IPFS Embed
ipfs-embed = { git = "https://github.com/ipfs-rust/ipfs-embed.git", rev = "a852c5f637dfb08a97d5a08a08cc86e81f5c9d96" }
libipld = "0.8"
