name: Rust

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Nightly toolchain
        run: rustup toolchain install nightly --component clippy
      - name: Lint
        run: cargo fmt -- --check
      - name: Clippy Warnings
        run: cargo +nightly clippy --all-targets --all-features -- -D warnings
      - name: Build
        run: cargo +nightly build
      - name: Run tests
        run: cargo +nightly test

