name: Rust

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1
      - uses: rui314/setup-mold@v1

      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: echo "Temporarily disabled tests" # cargo test
